### ISSUE TITLE
Another project for CSV-to-YNAB conversion

### ISSUE THREAD

**Issue by torbengb** [scottrobertson/barclays-to-ynab#2]
Hello Scott!
I've seen that you have a YNAB repository on GitHub. Have you seen that there are many similar projects? There is one in particular that could be very interesting for you: "bank2ynab"
https://github.com/torbengb/bank2ynab/blob/develop/README.md

If you could provide a sample CSV export (anonymized) then we could easily create the converter for your bank, too!

We would also like to know the default filename for the exported CSV, so we can identify it and use the proper converter.

Let me know what you think!
Best regards from snowy Austria,
Ben

**Comment by scottrobertson** [comment]
Hey @torbengb 

I will be honest, i have not used this project in many many years. I use https://github.com/scottrobertson/fintech-to-ynab to import directly into YNAB via the teller.io API. Also, Barclays is supported in YNAB directly.

**Comment by torbengb** [comment]
Hi Scott - thank you for this fast response! Glad to hear that Barclays is directly supported, then we can strike it from our list.
